### ISSUE TITLE
Incorrect quota reported in Input

### ISSUE THREAD

**Issue by nicogodet** [MerginMaps/server#16]
![image](https://user-images.githubusercontent.com/39594821/124579886-dad35e00-de4f-11eb-9549-2201c7aa7b6f.png)

![image](https://user-images.githubusercontent.com/39594821/124580091-1110dd80-de50-11eb-9687-01b6a7c8f8c8.png)

**Comment by varmar05** [comment]
@jozef-budac could you please verify this was fixed with new workspace approach?

**Comment by jozef-budac** [comment]
@varmar05 Yes, it is still a problem for the workspace. I will create ClickUp task for that

**Comment by tomasMizera** [comment]
This should now be fixed
